services:
    app:
        build: .
        restart: unless-stopped
        environment:
            APP_ENV: production
            APP_DEBUG: "true"
            APP_KEY: "base64:lQOzoN4aYUTmI/NU/PdMiZ8oJajhY1AOv1R68OplC0A="
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: contacts
            DB_USERNAME: pguser
            DB_PASSWORD: sRty$5PouI
            APP_URL: https://skvosnyak-php-laboratory-work-7581.twc1.net/
        ports:
            - "8080:80"
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            interval: 5s
            timeout: 5s
            retries: 10
